### PR TITLE
General fixes through tree-view, tabs, colors and scrollbar adjusts

### PR DESCRIPTION
**Pull request by rpichioli**
Some general theme fixes. 
This pull request is working with general text colors (ui-variables), scrollbar changes (the same sent in #3), mouse cursors in tabs and it's panel, and tree-view (according to the issue related in #1).

### CODE REVIEW

**Comment by rpichioli** [comment]
Hi @dangayle, can you deploy a new repository release? Thanks!

**Comment by dangayle** [comment]
Oh yeah, I forgot I had to do that. Thanks for the reminder.

**Comment by rpichioli** [comment]
You're welcome :)

**Comment by dangayle** [comment]
Pushed, but I just now noticed that the top tabs aren't working properly :(

-- Dan

**Pull request merged**
